name: Deploy Mainnet Subgraph

on:
  workflow_dispatch:
  push:
    branches: [ "elektrik-phoenix-v2" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn install

    - name: Deploy
      run: |
        npx npm run codegen
        npx npm run build
        npx npm run create-real-mainnet
        npx npm run deploy-mainnet ${{ github.run_number }}